import { Cube } from "./classes/Cube";

// let c = new Cube('DLLFUBDRFULUURLLBDLDRRFLRFFDRUFDRBUBBUFBLUUDFBFLDBDRBR');

// let c = new Cube('FUFUUURUULRLBRLBLFBFBDFRUDDBFLFDBFRRLLDFLBDRRDBUDBLUDR');
// let c = new Cube('UUFUUULUFDRRLRFDDBUFLRFDFLBRFRDDRLBLBLFLLFBBDUBRDBBURD');
// let c = new Cube('RUFUUURUBURUBRBRDLUFLLFRURDRFBFDLLRDDLBBLFBDFLBFDBLFDD');
let c = new Cube();
c.randomize();
console.log(c.solve());
// console.log(c.getMoves());